### ISSUE TITLE
Reference not imported!

### ISSUE THREAD

**Issue by alexsilva** [jbittel/django-ldap-sync#3]
[#1 ImproperlyConfigured](https://github.com/jbittel/django-ldap-sync/blob/master/ldap_sync/management/commands/syncldap.py#L65)

[#2 ImproperlyConfigured](https://github.com/jbittel/django-ldap-sync/blob/master/ldap_sync/management/commands/syncldap.py#L61)

**Comment by jbittel** [comment]
Whoops, thanks for catching that!
